Fixing setup.py error when installing couchdbkit package.
* Fixed warning:

    warning: no files found matching '*' under directory 'docs'

* Fixed exception:

    When installing couchdbkit from github this exception is outputted:

        Traceback (most recent call last):
          File "/home/sirex/devel/manoseimas/manoseimas.lt/parts/couchdbkit/couchdbkit/__init__.py", line 10, in <module>
            from .resource import  RequestFailed, CouchdbResource
          File "/home/sirex/devel/manoseimas/manoseimas.lt/parts/couchdbkit/couchdbkit/resource.py", line 25, in <module>
            from restkit import Resource, ClientResponse
        ImportError: No module named restkit

    This error is caused by this line from setup.py:

        from couchdbkit import __version__

    Of course couchdbkit/__init__.py file catches this import exception and
    installs correctly, but when installing, such errors should not be
    outputted.

    To avoid showing this exception I did some checking if this import was made
    by setup.py file.